# Generated by Django 3.2.8 on 2022-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода')),
                ('film_ratings', models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('link', models.CharField(blank=None, max_length=100, verbose_name='Ссылка')),
            ],
        ),
    ]
